games-rule-api:
  postgres:
    host: "{{ .Release.name }}-postgres-rw"
    port: 5432
    dbName: games
    passwordSecret:
      name: "{{ .Release.name }}-postgres-app"
      key: password
    userSecret:
      name: "{{ .Release.name }}-postgres-app"
      key: username

minio:
  rootUser: admin
  rootPassword: "" # If empty, a random password will be generated
  servers: 1
  volumesPerServer: 1
  storageSize: 10Gi
  storageClassName: local-path

  loadBalancer:
    enabled: true
    apiIp: 192.168.0.254 # IP for MinIO API service
    consoleIp: 192.168.0.249 # IP for Console service

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  buckets:
    - name: boardgames
      objectLocking: false

  users:
    - accessKey: gamesuser
      secretKey: gamesuser-password
