apiVersion: v1
kind: Service
metadata:
  name: {{ include "games-rule-api.fullname" . }}
  labels:
    {{- include "games-rule-api.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  serviceMetadata:
    minioServiceAnnotations:
      metallb.universe.tf/loadBalancerIPs: {{ .Values.service.loadBalancer.apiIp | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "games-rule-api.selectorLabels" . | nindent 4 }}
